/**
 * Created by pandey on 11/02/17.
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

 Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
 10: 1,2,5,10
 15: 1,3,5,15
 21: 1,3,7,21
 28: 1,2,4,7,14,28
 We can see that 28 is the first triangle number to have over five divisors.

 What is the value of the first triangle number to have over five hundred divisors?
 */
public class eulerProblem12 {
    public static void main(String[] args) {
        long startTime= System.currentTimeMillis();
        boolean continueLoop = true;
        int divisorCount =0;
        int i=1;
        while (continueLoop)
        {
            int ithTriangleNumber = i*(i+1)/2;
            if(ithTriangleNumber >1000)
            {
                divisorCount =0;
                for(int j = 1 ; j<=Math.sqrt(ithTriangleNumber) ; j++) {
                    if (ithTriangleNumber % j == 0) {
                        divisorCount++;
                    }

                    if (divisorCount > 250) {
                        System.out.println("Triangle number with over 500 divisors are : " + ithTriangleNumber);
                        continueLoop = false;
                        break;
                    }
                }
                //System.out.println("Triangle number for int : " +i+ " is : "+ ithTriangleNumber+" with :  "+divisorCount+" divisors.");
            }

            i++;
        }

        long endTime= System.currentTimeMillis();
        long runtime = endTime-startTime;

        System.out.println("RunTime for problem 9 in ms : " + runtime );
    }
}
